### ISSUE TITLE
fastqp stuck with very long consensus fastq file 

### ISSUE THREAD

**Issue by peterdfields** [mdshw5/fastqp#18]
I'm trying to generate a plot of fastq quality along a very long (800kb) assembly sequence. When I run  fastqp I get the following and seemingly no non-stdout output:

At 1775681 bytes per read of 887828 length we estimate 1 reads in input file.
Bin size (-s) set to 1.

It might be the case that this is simply not the appropriate tool. The goal is simply a summary of support of given nucleotide calls along the de novo reference. All advice is much appreciated!

**Comment by mdshw5** [comment]
Yes, @peterdfields, I believe this is the wrong tool for your task. If there is only one sequence in the input file, fastqp will likely error when calculating base quality quantiles.

**Comment by peterdfields** [comment]
Makes sense. Thanks for your reply!
