### ISSUE TITLE
Plotting raises exceptions with matplotlib-2.2.2

### ISSUE THREAD

**Issue by unode** [mdshw5/fastqp#31]
Hi all,

With matplotlib 2.1.0 I get `MatplotlibDeprecationWarning: The set_axis_bgcolor function was deprecated in version 2.0. Use set_facecolor instead.`. With the latest `matplotlib-2.2.2` it now raises an exception.

Is there a recommended matplotlib version?

**Comment by mdshw5** [comment]
Hmmm. I’ll just fix this and push an update since I think pinning package versions isn’t a great idea for end users.

**Comment by mdshw5** [comment]
I’ve fixed this in the latest version.
