### ISSUE TITLE
not detecting adapter seq 

### ISSUE THREAD

**Issue by divyoj** [mdshw5/fastqp#32]
Hi!

We are doing riboseq analysis on some fastq files. We are using Fastp for adapter identification and removal. But, we are facing some problems. fastp is able to remove the adapter sequences only if the adapter seq is given in the command line as an argument. It is not able to detect the adapter and remove it by itself and is giving the output as adapter is not detected. The sra file used, adapter seq and codes are as follows:

SRA file : SRR810103 (fastq size 31.6GB)

adapter seq: TCGTATGCCGTCTTCTGCTTG

./fastp -i ./SRR810103.fastq -a TCGTATGCCGTCTTCTGCTTG -q 33 -w 10 -o./output.fastq

./fastp -i ./SRR810103.fastq -w 10 -o ./output.fastq

Can you please help us?

Eagerly waiting for your help!

**Comment by mdshw5** [comment]
I think you're looking for a different repository: https://github.com/OpenGene/fastp. You might also try asking this question on http://biostars.org.

You could use the fastqp utility in this repository to identify any adapter sequence in the reads, and it's possible that the SRA project you're downloading has already adapter trimmed. If you FASTQ file has a read lengths that are not all equal it's likely that some trimming has been done.

Good luck!
